#lang racket

(require ( planet "sicp.ss" ( "soegaard" "sicp.plt" 2 1)))

(define (make-segment v1 v2) (cons v1 v2))
(define (make-vect x y) (cons x y))

(define outline-segments (list (make-segment (make-vect 0.0 0.0) (make-vect 0.99 0.0))
                               (make-segment (make-vect 0.0 0.0) (make-vect 0.0 0.99))
                               (make-segment (make-vect 0.0 0.99) (make-vect 0.99 0.99))
                               (make-segment (make-vect 0.99 0.0) (make-vect 0.99 0.99))))
(define outline (segments->painter outline-segments))
(paint outline)

(define cross-segments (list (make-segment (make-vect 0 0) (make-vect 1 1))
                             (make-segment (make-vect 1 0) (make-vect 0 1))))
(define cross (segments->painter cross-segments))
(paint cross)

(define diamond-segments (list (make-segment (make-vect 0.0 0.5) (make-vect 0.5 1))
                               (make-segment (make-vect 0.5 1) (make-vect 1 0.5))
                               (make-segment (make-vect 1 0.5) (make-vect 0.5 0))
                               (make-segment (make-vect 0.5 0) (make-vect 0.0 0.5))))
(define diamond (segments->painter diamond-segments))
(paint diamond)

(define wave-segments (list (make-segment (make-vect 0.0 0.8) (make-vect 0.2 0.6))
                            (make-segment (make-vect 0.2 0.6) (make-vect 0.3 0.65))
                            (make-segment (make-vect 0.3 0.65) (make-vect 0.35 0.65))
                            (make-segment (make-vect 0.35 0.65) (make-vect 0.3 0.8))
                            (make-segment (make-vect 0.3 0.8) (make-vect 0.35 1))
                            (make-segment (make-vect 0.65 1) (make-vect 0.7 0.8))
                            (make-segment (make-vect 0.7 0.8) (make-vect 0.65 0.65))
                            (make-segment (make-vect 0.65 0.65) (make-vect 0.7 0.65))
                            (make-segment (make-vect 0.7 0.65) (make-vect 1 0.35))
                            (make-segment (make-vect 1 0.2) (make-vect 0.7 0.45))
                            (make-segment (make-vect 0.7 0.45) (make-vect 0.75 0))
                            (make-segment (make-vect 0.6 0) (make-vect 0.5 0.3))
                            (make-segment (make-vect 0.5 0.3) (make-vect 0.4 0))
                            (make-segment (make-vect 0.25 0) (make-vect 0.3 0.45))
                            (make-segment (make-vect 0.3 0.45) (make-vect 0.2 0.4))
                            (make-segment (make-vect 0.2 0.4) (make-vect 0 0.65))))
(define wave (segments->painter wave-segments))
(paint wave)